=== jecki/DHParser/experimental/Bayerisches_Woerterbuch/BWB_17-11-16.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD-Design: UW -->
<!-- Stand: 16.11.2017 -->

<!-- PARAMETER ENTITIES -->
<!-- Attribute -->
<!ENTITY % belegt  "belegt (ja | nach1958 | ausgestorben) 'ja'" >
<!ENTITY %  bezirk-muss  "bezirk  (OB | NB | OP | OF | MF | SCH | Gesamtgebiet | Restgebiet | SR)  #REQUIRED" >
<!ENTITY %  bezirk-kann  "bezirk  (OB | NB | OP | OF | MF | SCH | Gesamtgebiet | Restgebiet | SR)  #IMPLIED" >
<!ENTITY %  häufigkeit "häufigkeit  (vielf. | mehrf. | vereinz. | einBeleg) #IMPLIED" >
<!ENTITY % id  "id ID  #REQUIRED" >
<!ENTITY % idref "ziel  IDREF  #REQUIRED" >
<!ENTITY % landkreis "landkreis (M | FS | WAS | WOR | VIT | NEW | SR | DGF | GRI | VOF | R | STA | GRA | R | RO | DEG | DAH | IN | WM | EIH | HEB | HIP | N | WUG | LL | SC | KEH | BT |PEG | FDB | FFB | REH | NM | PAR)  #IMPLIED" >
<!ENTITY % ort-landkreis  "ort-landkreis (Chiemgau | BayWald | 
                    München_M | Freising_FS | Wasserburg-WAS | Wolfratshausen_WOR | Prackenbach-VIT | Rothenstadt-NEW | Hankfn-SR | Mengkfn-DGF | Mittich-GRI | Söldenau-VOF | Brennbg-R | Oalting-STA | Grafenau-GRA | Rgbg-R | Frasdf-RO | Iggensbach-DEG)  #IMPLIED" >
<!ENTITY %  phrase-art  "phrase-art  (Reim | Schnaderhüpfel | Schnaderhüpfeln | Spruch | Sprüche | Rätsel | Bauern-Wetterregel | Bauern-Wetterregeln | Scherzvers | Scherzverse | Kindervers |Kinderverse | Grußformel | Grußformeln | Dankformel | Dankformeln | Ortsneckerei | Ortsneckereien | Spiel | Spiele | Ausruf | Ausrufe)  #IMPLIED"  >
<!ENTITY %  quelle-art  "quelle-art (nichts | ähnlich) 'nichts'" >
<!ENTITY %  sonst  "sonst  CDATA  #IMPLIED" >


<!-- Elemente -->
<!ENTITY % zeichen  "hoch | tief" >


<!-- GRUNDSTRUKTUR -->

<!ELEMENT  BWB  (artikel+) >

<!ELEMENT  artikel   (lemma-position, bedeutung-position+, (etymologie-position | lautung-position | literatur-position | ableitung-position | erlaeuterung-position)+, komposita-position?, verfasser) >
<!ATTLIST  artikel  %id; 
               sort  CDATA #IMPLIED >

<!-- Lemma-Position -->
<!ELEMENT  lemma-position (lemma, lemma-variante*, lemma-verweise?, grammatik) >
<!-- Lemma-Verweise dienen der Generierung von Verweisartikel in der Printausgabe; in der Online-Ausgabe gehen sie in das Lemma-Suchregister ein -->
<!ELEMENT  lemma-verweise  (lemma-variante+) >

<!ELEMENT  lemma  (#PCDATA | hoch)* >
<!ATTLIST  lemma  %belegt; >

<!--In lemma-variante stets die Langform angeben, die in Suchindex soll.-->
<!ATTLIST  lemma-variante  %belegt; 
                            kurzform  CDATA  #IMPLIED >

<!ELEMENT  grammatik  EMPTY >
<!ATTLIST  grammatik  genus  (F | M | N)  #IMPLIED
		wortart  ( N | Vb | Adj | Adv)  #REQUIRED 
		numerus  ( Singular | Plural)  #IMPLIED 
		%belegt; >

<!-- Bedeutungs-Position -->
<!ELEMENT  bedeutung-position ((((bedeutung+ | (bedeutung-spezial+, form-spezial)), 
            ((verbreitung-position?, beleg-position) | bedeutung-position+),
            (erlaeuterung-position | literatur-position)*) | beleg-position), exkurs-position*, verweis-abb?) >
<!ATTLIST  bedeutung-position  
			%id;
			nr  CDATA  #IMPLIED > <!-- Nummerierung der Bedeutungen im Artikel -->

<!-- für Unter-Bedeutungen, auch geschachtelt -->
<!ELEMENT  bedeutung-variante  (bedeutung+, ((verbreitung-position, beleg-position) | bedeutung-variante+), verweis-abb?) >
<!ATTLIST  bedeutung-variante  
			%id;
			nr  CDATA  #IMPLIED >


<!ELEMENT  bedeutung  (#PCDATA | name-linne | verweis)* >
<!ATTLIST  bedeutung  %belegt; >
<!ELEMENT  name-linne  (#PCDATA) >
<!ELEMENT  bedeutung-spezial  (#PCDATA | verweis)* >
<!ELEMENT  form-spezial  (#PCDATA | beleg-typ | lemma-referenz)* >

<!ELEMENT  verbreitung-position (verbreitung-angabe+) >
<!ELEMENT  verbreitung-angabe  EMPTY >
<!ATTLIST  verbreitung-angabe  %belegt; 
		%häufigkeit; 
		%bezirk-muss; >

<!-- Beleg-Position -->
<!ELEMENT  beleg-position ((beleg-angabe+, phraseologie*) | phraseologie+) >
<!ELEMENT  beleg-angabe  (beleg-text, beleg-kontext?, beleg-quelle) >
<!ATTLIST  beleg-angabe  %belegt; >
<!ELEMENT  beleg-text  (#PCDATA | beleg | kontext | glossierung | lemma-referenz | %zeichen;)* >
<!ELEMENT  beleg-kontext  (#PCDATA | beleg | glossierung | lemma-referenz | %zeichen;)* >
<!ATTLIST  beleg-kontext  %belegt; anfuehrung (ja | nein)  #IMPLIED > <!-- Anführung zwingend? -->
<!ELEMENT  kontext  (#PCDATA | beleg | %zeichen;)* >
<!ATTLIST  kontext  %belegt; anfuehrung (ja | nein)  #IMPLIED > <!-- Anführung zwingend? -->


<!ELEMENT  beleg-quelle  (beleg-region | literatur-quelle | beleg-zeit)+ >
<!-- in der Printausgabe werden die Landkreise für identische Orte nicht ausgegeben -->
<!ELEMENT  beleg-region  (#PCDATA)  >
<!ATTLIST   beleg-region  %ort-landkreis;
                                               %bezirk-kann; 
                                               %quelle-art; 
                                               >
<!ELEMENT  beleg-zeit  (#PCDATA) >

<!ELEMENT  phraseologie  (intro?, (phrase | phraseologie)+) >
<!ELEMENT  phrase  ((beleg-typ, bedeutung*, verbreitung-angabe*)?, beleg-angabe+) >
<!ATTLIST  phrase  %phrase-art; 
                                    %sonst;>
<!ELEMENT  intro  (#PCDATA | abk | lemma-referenz)* >
<!ELEMENT  phrase-text  (#PCDATA | lemma-referenz | %zeichen;)* >
<!ELEMENT  phrase-bedeutung  (#PCDATA | lemma-referenz | %zeichen;)* >

<!-- Erläuterungsposition / Sachlage -->
<!ELEMENT  erlaeuterung-position  (#PCDATA | verweis | lemma-referenz | abk | beleg-typ | literatur-quelle | verbreitung-angabe)* >

<!-- Exkurs: Sachliches, Volkskundliches -->
<!ELEMENT  exkurs-position   (intro?, exkurs+, literatur-position?) >
<!ELEMENT  exkurs   (#PCDATA | verweis | lemma-referenz | literatur-quelle | beleg)* >

<!-- Etymologie-Position --> 
<!ELEMENT  etymologie-position  (#PCDATA | lemma-form | beleg-quelle | abk | verweis)* >
<!ELEMENT  lemma-form   (#PCDATA) >
<!ATTLIST  lemma-form  sprache  CDATA  #IMPLIED >

<!-- Lautungs-Position -->
<!ELEMENT  lautung-position (lautung-angabe)+ >
<!ELEMENT  lautung-angabe (#PCDATA | beleg-typ | verbreitung-region | literatur-quelle)* >
<!ATTLIST  lautung-position  typ   (ltg | lautg-formen) "ltg" >
<!ELEMENT  verbreitung-region  EMPTY  >
<!ATTLIST  verbreitung-region %landkreis;  >

<!-- Literatur-Position -->
<!ELEMENT  literatur-position (literatur-gruppe+ | (literatur-quelle | sammlung-quelle)+) >
<!ELEMENT  literatur-gruppe  (literatur-quelle+ | sammlung-quelle+) >
<!ELEMENT  sammlung-quelle (#PCDATA) >
<!--<!ATTLIST  sammlung-quelle  typ  (eigeneBefragung | Literatur)  #IMPLIED >
-->
<!-- Ableitungsposition -->
<!ELEMENT  ableitung-position  (#PCDATA | %zeichen; | lemma-form | verweis)* >

<!-- Komposita-Position -->
<!ELEMENT  komposita-position (kompositum+) >
<!ELEMENT  kompositum   (lemma-kompositum+, lemma-kompositum-variante*, bedeutung-position+, lautung-position?, literatur-position?) >
<!ELEMENT  lemma-kompositum  (bestimmungsteil, lemma-referenz) >
<!ELEMENT  lemma-kompositum-variante  (bestimmungsteil, lemma-referenz) >
<!ELEMENT  bestimmungsteil  (#PCDATA) >

<!ATTLIST  kompositum 
				typ (mehrfach | einfach | doppel) "einfach" 
				%id; >

<!-- Verfasser -->
<!ELEMENT  verfasser   EMPTY >
<!ATTLIST  verfasser  kuerzel  (EBF | AR | HUS | HSt | BUS | AS | JD) #REQUIRED >


<!-- ******************************************* -->
<!-- Einzelangaben -->

<!ELEMENT  lemma-referenz (#PCDATA) >
<!ATTLIST  lemma-referenz 
                abk      CDATA  #REQUIRED 
                vollform CDATA  #REQUIRED 
                >

<!-- allgemein verwendet -->
<!ELEMENT  abk  (#PCDATA) >
<!ATTLIST  abk langform CDATA #REQUIRED >

<!ELEMENT  autor (#PCDATA) >
<!ELEMENT  beleg  (#PCDATA | glossierung | %zeichen;)*  >
<!ELEMENT  beleg-typ  (#PCDATA | glossierung | lemma-referenz | %zeichen;)*  >
<!ELEMENT  glossierung (#PCDATA) >
<!ELEMENT  hoch  (#PCDATA) >
<!ELEMENT  literatur-quelle (#PCDATA | autor | %zeichen;)* >
<!ATTLIST  literatur-quelle  %quelle-art; >
<!ELEMENT  tief  (#PCDATA) >

<!ELEMENT  verweis (#PCDATA | lemma-referenz | %zeichen;)* >
<!ELEMENT  verweis-abb (#PCDATA | lemma-referenz | %zeichen;)* >
<!ATTLIST  verweis  %idref; >

=== jecki/DHParser/experimental/Bayerisches_Woerterbuch/XML-BWB_Testdaten_17-11-16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BWB SYSTEM "BWB_17-11-16.dtd" >
<BWB>

<!--ein VERB !!!-->


<artikel id="tändeln">
<lemma-position>
<lemma>tändeln</lemma>
<!--In lemma-variante stets die Langform angeben, die in Suchindex soll.-->
<lemma-variante kurzform="-a-">tandeln</lemma-variante>
<grammatik wortart="Vb"/></lemma-position>

<bedeutung-position nr="1">
<bedeutung>(mit Tauschwaren od. Trödel) Handel treiben</bedeutung>
<verbreitung-position><verbreitung-angabe bezirk="OB" häufigkeit="vielf."/>
<verbreitung-angabe bezirk="NB" häufigkeit="mehrf."/>
<verbreitung-angabe bezirk="OP" häufigkeit="vereinz."/>
<verbreitung-angabe bezirk="MF" häufigkeit="vereinz."/></verbreitung-position>


<beleg-position>
<beleg-angabe belegt="nach1958"><beleg-text>dea’ma Buiddl danddln?</beleg-text>
<beleg-quelle><beleg-region><ort>Dachau</ort><landkreis>DAH</landkreis></beleg-region></beleg-quelle></beleg-angabe>

<beleg-angabe><beleg-text><kontext anfuehrung="ja">Trödelwaare verkaufen … <beleg>dándln</beleg></kontext></beleg-text><beleg-quelle></beleg-quelle></beleg-angabe>
<beleg-angabe><beleg-text>dạndln </beleg-text><beleg-quelle><beleg-region><ort>Baar </ort><landkreis>ND</landkreis></beleg-region><literatur-quelle>SBS X,8</literatur-quelle><beleg-zeit></beleg-zeit></beleg-quelle></beleg-angabe>
<beleg-angabe><beleg-text>min Läid <kontext>(Feuer)</kontext> dandln <kontext anfuehrung="ja">zündeln</kontext></beleg-text><beleg-quelle></beleg-quelle></beleg-angabe>


</beleg-position>
</bedeutung-position>
<bedeutung-position nr="2">
<bedeutung>spielen</bedeutung>
<bedeutung-variante nr="2a" id="tändeln-2a">
<bedeutung>mit Spielsachen spielen</bedeutung></bedeutung-variante></bedeutung-position>
</artikel>




























<!--nun ein neuerer Artikel-->
<artikel id="Darm" sort="Därm">
<lemma-position>
<lemma>Darm</lemma>
<lemma-verweise>
<lemma-variante>Gedärm</lemma-variante><!--Generieren von Verweisartikeln-->
<lemma-variante>Daram</lemma-variante></lemma-verweise>
<grammatik wortart="N" genus="M"/>
</lemma-position>
<bedeutung-position id="Darm-00"><bedeutung belegt="ausgestorben">nnnhh</bedeutung>
<beleg-position><beleg-angabe><beleg-text></beleg-text><beleg-quelle></beleg-quelle></beleg-angabe></beleg-position>
</bedeutung-position>
<bedeutung-position nr="1" id="Darm-1"><!--Sprungziel für Verweise-->
<bedeutung>Darm, Gedärm</bedeutung>
<verbreitung-position>
<verbreitung-angabe bezirk="Gesamtgebiet" häufigkeit="vielf."/>
<verbreitung-angabe häufigkeit="vielf." bezirk="OB"/> 
</verbreitung-position>


<beleg-position><beleg-angabe><beleg-text>er hats im Darm </beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Wasserburg-WAS"></beleg-region><beleg-zeit>9.Jh</beleg-zeit><literatur-quelle></literatur-quelle></beleg-quelle></beleg-angabe> 
<beleg-angabe><beleg-text><kontext anfuehrung="ja">für Leberwürste die <beleg>Darm</beleg> des Schweins</kontext></beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Prackenbach-VIT"></beleg-region><literatur-quelle></literatur-quelle><beleg-region></beleg-region></beleg-quelle></beleg-angabe>

<beleg-angabe><beleg-text>Därmer hobn si vaschlinglt</beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Rothenstadt-NEW"></beleg-region></beleg-quelle></beleg-angabe>

<beleg-angabe><beleg-text>vom Wasser kröigt ma’ bloue Daarma</beleg-text>
<beleg-quelle><literatur-quelle>Oberpfalz 80 (1992) 145</literatur-quelle></beleg-quelle></beleg-angabe>

<beleg-angabe><beleg-text>intestinis … indarmum</beleg-text>
<beleg-quelle><beleg-zeit>8./9.Jh.</beleg-zeit><literatur-quelle>StSG. I,154,32</literatur-quelle></beleg-quelle></beleg-angabe>

<beleg-angabe><beleg-text>chrebs dærmlein streket sich … vntz <kontext>[bis]</kontext> an daz end seins swantzes</beleg-text>
<beleg-quelle><literatur-quelle>KONRADvM BdN 276,1f.</literatur-quelle></beleg-quelle></beleg-angabe>


<beleg-angabe><beleg-text>in stechen, daß im die därm heraus sollen geen </beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Hankfn-SR"></beleg-region><beleg-zeit>1550</beleg-zeit><literatur-quelle>HELM Obrigkeit 171</literatur-quelle></beleg-quelle></beleg-angabe>


<phraseologie>
<phrase><beleg-angabe><beleg-text>dö dickn Da(r)m <kontext>Dickdärme</kontext></beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Mengkfn-DGF"></beleg-region></beleg-quelle></beleg-angabe></phrase>



<phrase><beleg-typ>Dünner <lemma-referenz abk="D." vollform="Darm">D.</lemma-referenz> </beleg-typ>
 
<bedeutung>Dünndarm</bedeutung>
<verbreitung-angabe bezirk="NB" häufigkeit="vereinz."/><!--Doppelpunkt-->
<beleg-angabe><beleg-text>dö dina Da(r)m</beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Mittich-GRI"></beleg-region></beleg-quelle></beleg-angabe>
</phrase>
<phrase><beleg-angabe belegt="nach1958"><beleg-text>toter Darm</beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Söldenau-VOF"></beleg-region></beleg-quelle></beleg-angabe></phrase>
<phrase><beleg-angabe belegt="nach1958"><beleg-text>Wöi a Doam <kontext anfuehrung="ja">lang und dünn</kontext></beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Brennbg-R"></beleg-region></beleg-quelle></beleg-angabe></phrase>


<phrase><beleg-angabe><beleg-text>dẹị siaht wẹị a asgschdrafda Doarm <kontext anfuehrung="ja">sie ist sehr mager</kontext></beleg-text>
<beleg-quelle><literatur-quelle>KONRAD nördl.Opf. 63</literatur-quelle>
<literatur-quelle quelle-art="ähnlich">KAPS Welt d.Bauern 61</literatur-quelle></beleg-quelle></beleg-angabe>
<beleg-angabe><beleg-text>dea schat hea wia wen a grad an Doam het dua und dua <kontext anfuehrung="ja">ist bleich und mager</kontext></beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Iggensbach-DEG"></beleg-region>
<!--Hier nur Landkreis, daher als "Bezirk" angelegt ...-->
<beleg-region quelle-art="ähnlich" bezirk="SR"></beleg-region></beleg-quelle></beleg-angabe>
</phrase>
</phraseologie>
</beleg-position>
</bedeutung-position>
<!--zweite Bedeutung-->
<bedeutung-position nr="2" id="Darm-2">
<bedeutung>aus Tierdarm Bestehendes</bedeutung>

<bedeutung-position nr="2a" id="Darm-2a">
<bedeutung>Wursthaut</bedeutung>

<verbreitung-position>
<verbreitung-angabe bezirk="MF" häufigkeit="vielf."/>
<verbreitung-angabe bezirk="NB" häufigkeit="mehrf." belegt="nach1958"/>
<verbreitung-angabe bezirk="OP" häufigkeit="mehrf."/>
<verbreitung-angabe bezirk="Restgebiet" häufigkeit="vereinz."/></verbreitung-position>

<beleg-position>
<beleg-angabe><beleg-text>Darm, Saitling</beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Oalting-STA"></beleg-region></beleg-quelle></beleg-angabe>
<beleg-angabe belegt="nach1958"><beleg-text>i hed no an Badzn Gwuaschdad <kontext>(Wurstteig)</kontext> då, bringsdas no ei öd Darm?</beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Grafenau-GRA"></beleg-region></beleg-quelle></beleg-angabe></beleg-position>
</bedeutung-position>
<bedeutung-position nr="2b" id="Darm-2b"><bedeutung>Darmsaite</bedeutung>
<verbreitung-position><verbreitung-angabe bezirk="NB" häufigkeit="vereinz."/></verbreitung-position><!--: ????--><beleg-position><beleg-angabe><beleg-text>Soatn, Darm <kontext>auf Streichinstrumenten</kontext></beleg-text>
<beleg-quelle><beleg-region ort-landkreis="Rgbg-R"></beleg-region></beleg-quelle></beleg-angabe></beleg-position></bedeutung-position>
</bedeutung-position>
<bedeutung-position nr="3" id="Darm-3"><bedeutung>lange schmale Fläche, schmaler Raum</bedeutung>
<verbreitung-position><verbreitung-angabe bezirk="OB" häufigkeit="vielf."/>
<verbreitung-angabe bezirk="Restgebiet" häufigkeit="mehrf."/></verbreitung-position>
<beleg-position><beleg-angabe><beleg-text>grod a so a schmoicha Darm <kontext>sehr schmales Feld</kontext></beleg-text>
<beleg-quelle><beleg-region><ort>Frasdf</ort><landkreis>RO</landkreis></beleg-region></beleg-quelle></beleg-angabe></beleg-position></bedeutung-position>


<etymologie-position>
 Ahd. <lemma-form typ="ahd.">darm</lemma-form>, mhd. 
<lemma-form typ="mhd.">darm</lemma-form> <abk langform="stark männlich ">stm.</abk>, germ. Wort <abk langform="indogermanisch">idg.</abk> Herkunft; <beleg-quelle><literatur-quelle>KLUGE-SEEBOLD 181</literatur-quelle></beleg-quelle></etymologie-position>


<lautung-position typ="ltg">
