=== jecki/DHParser/examples/MLW/XML/MLW-DTD_2017-07-12.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD für MLW Erfassung neuer Artikel -->
<!-- erstellt von Ursula Welsch, BADW -->
<!-- Stand: 6.7.2017 -->

<!-- Parameter-Entities -->
<!ENTITY % textauszeichnungen   "kursiv | gesperrt | gerade" >

<!-- Lexikon -->
<!ELEMENT  MLW-test  (artikel)+  >

<!-- Artikel -->
<!ELEMENT  artikel  (lemma-position, artikelkopf?, bedeutung-position, verweis-position?, sub-artikel*, artikel-verfasser) >
<!ATTLIST   artikel   xml:id   ID  #REQUIRED >

<!-- =========================-->
<!-- Lemma-Ansatz -->
<!-- =========================-->
<!ELEMENT  lemma-position  (((lemma, lemma-varianten?, grammatik-position) | (lemma-position | zusatz)+), etymologie-position?) >
<!ATTLIST  lemma-position  nr   CDATA  #IMPLIED >

<!-- Lemma -->
<!ELEMENT  lemma  (#PCDATA) >
<!ATTLIST  lemma 
        klassisch  (ja | nein)   "ja"
        gesichert  (ja | nein)    "ja" 
        >

<!-- Lemma-Varianten -->
<!ELEMENT  lemma-varianten  (lemma-variante+, zusatz?) >
<!ELEMENT  lemma-variante  (#PCDATA)  >
<!ATTLIST   lemma-variante  kurz   CDATA   #IMPLIED  >

<!-- Grammatik-Position -->
<!ELEMENT  grammatik-position  (grammatik, grammatik-varianten?)  >

<!-- Grammatikangaben -->
<!ELEMENT  grammatik  (#PCDATA) >
<!ATTLIST  grammatik 
        wortart  (nomen | adjektiv | verb | adverb | praep)  #REQUIRED 
        klasse  (us-i | a-ae | um-i | x-cis)  #IMPLIED 
        genus  (m | f | n)  #IMPLIED 
        konjugation  (are | ere | ire | irreg)  #IMPLIED
        >
 
<!-- Grammatik-Varianten -->
<!ELEMENT  grammatik-varianten  (grammatik-variante+) >
<!ELEMENT  grammatik-variante  (grammatik, beleg+) >

<!-- Etymologie-Position -->
<!ELEMENT  etymologie-position  (etymologie-variante+) >
<!ELEMENT  etymologie-variante  (etymologie-besonderheit?, etymologie?, beleg)  >
<!ELEMENT  etymologie  (#PCDATA) >
<!ATTLIST   etymologie-variante  sprache (griech | lat)  #IMPLIED >
<!ELEMENT  etymologie-besonderheit  (#PCDATA)  >


<!-- =========================-->
<!-- Artikelkopf -->
<!-- =========================-->
<!ELEMENT  artikelkopf ((schreibweisen-position, struktur-position?, gebrauch-position?, metrik-position?, verwechslung-position?) | 
        (struktur-position, gebrauch-position?, metrik-position?, verwechslung-position?) | 
        (gebrauch-position, metrik-position?, verwechslung-position?) | 
        (metrik-position, verwechslung-position?) | 
        verwechslung-position) >

<!-- Schreibweisen-Position -->
<!ELEMENT  schreibweisen-position  (schreibweisen-variante)+ >
<!ELEMENT  schreibweisen-variante  (schreibweise-besonderheit?, schreibweise, (zusatz, schreibweise)*, (beleg, (zusatz | beleg)*)?) >
<!ELEMENT  schreibweise-besonderheit  (#PCDATA) >
<!ELEMENT  schreibweise  (#PCDATA) >
<!ATTLIST   schreibweise-besonderheit  typ  (script | form | script-form | OFFEN)  #IMPLIED >

<!-- Position für Strukturelle/Grammatische Besonderheiten -->
<!ELEMENT  struktur-position  (struktur-variante+) >
<!ELEMENT   struktur-variante  (struktur-besonderheit?, struktur?, beleg)  >
<!ELEMENT  struktur-besonderheit  (#PCDATA) >
<!ELEMENT  struktur  (#PCDATA) >
<!ATTLIST   struktur-besonderheit  typ  (pendet | struct | struct-nota | OFFEN)  #IMPLIED >

<!-- Position zu Gebrauchs-Besonderheiten -->
<!ELEMENT  gebrauch-position  (gebrauch-variante, zusatz?)+ >
<!ELEMENT  gebrauch-variante  (gebrauch-besonderheit?, beleg+)  >
<!ELEMENT  gebrauch-besonderheit  (#PCDATA) >
<!ATTLIST   gebrauch-besonderheit  typ  (usu | partic | OFFEN)  #IMPLIED >

<!-- Position zu Metrisch / Rhythmischen Besonderheiten -->
<!ELEMENT  metrik-position  (metrik-variante+) >
<!ELEMENT  metrik-variante  (metrik-besonderheit?, metrik?, beleg)  >
<!ELEMENT  metrik-besonderheit  (#PCDATA) >
<!ELEMENT  metrik  (#PCDATA) >
<!ATTLIST   metrik-besonderheit   typ  (metr | rhythm | OFFEN)  #IMPLIED >

<!-- Position zu Verwechselungsgefahren -->
<!ELEMENT  verwechslung-position  (verwechslung-variante+) >
<!ELEMENT  verwechslung-variante  (verwechslung-besonderheit?, verwechslung?, beleg)  >
<!ELEMENT  verwechslung-besonderheit  (#PCDATA) >
<!ELEMENT  verwechslung  (#PCDATA) >
<!ATTLIST   verwechslung-besonderheit  typ  (confunditur | OFFEN)  "confunditur" >

<!-- =========================-->
<!-- Hauptteil: Bedeutungsposition -->
<!-- =========================-->
<!ELEMENT  bedeutung-position  (bedeutung+) >
<!ELEMENT  bedeutung  (((klassifikation, interpretament-zusatz?, interpretament?, interpretament-deutsch?) | (interpretament-zusatz) | (interpretament, interpretament-deutsch, interpretament-zusatz*)), (bedeutung | beleg-position)+) >
<!ELEMENT   klassifikation  (#PCDATA | verweis)*  >
<!ATTLIST  bedeutung  nr  CDATA  #REQUIRED  >

<!-- Interpretament -->
<!ELEMENT  interpretament  (#PCDATA) >
<!ELEMENT  interpretament-deutsch  (#PCDATA| verweis)* >
<!ELEMENT  interpretament-zusatz  (#PCDATA | verweis | interpretament | interpretament-deutsch)* >
<!ATTLIST  interpretament  typ  (lat | griech | botan)  "lat" >

<!-- Beleg-Position -->
<!ELEMENT  beleg-position  (beleg+, zusatz?) >

<!-- Verweisposition -->
<!ELEMENT  verweis-position  (verweis+)  >

<!-- Artikelverfasser -->
<!ELEMENT   artikel-verfasser  (#PCDATA)  >


<!-- =========================-->
<!-- Sub-Artikel, Sublemma -->
<!-- =========================-->
<!ELEMENT  sub-artikel  (lemma-position, bedeutung-position) >




<!-- =========================-->
<!--Elemente an verschiedenen Stellen der Struktur -->
<!-- =========================-->
<!-- Zusätze an verschiedenen Stellen der Struktur -->
<!ELEMENT  zusatz  (#PCDATA) >
<!ATTLIST   zusatz  typ  (adde | al | sim | saepe | vel | vel-rarius | OFFEN)  #REQUIRED >

<!-- Verweise an verschiedenen Stellen der Struktur -->
<!-- Der Inhalt des Verweises wird nicht ausgegeben!! Er dient nur der Orientierung - leider meckert Oxy auch einen Kommentar als PCDATA an ... -->
<!ELEMENT  verweis  (#PCDATA)  >
<!ATTLIST  verweis
        typ  (beleg | artikel | literatur)  #REQUIRED 
        ziel  CDATA  #REQUIRED
        >
        
<!-- Belege an verschiedenen Stellen der Struktur -->
<!--<!ELEMENT  beleg  (((beleg-quelle, beleg-text?) | beleg-text) | (verweis+, zusatz?)) >-->
<!ELEMENT  beleg  (((beleg-quelle, beleg-text?) | beleg-text) | verweis) >
<!-- Belegquelle -->
<!ELEMENT  beleg-quelle  (autor, werk, stelle, datierung?, edition?) >
<!ELEMENT  autor  (#PCDATA) >
<!ELEMENT  werk  (#PCDATA) >
<!ELEMENT  stelle  (#PCDATA | hoch)* >
<!ELEMENT  datierung  (#PCDATA) >
<!ELEMENT  edition  (#PCDATA) >
<!ATTLIST  beleg  
        id  ID  #REQUIRED 
        >
        
<!-- Belegtext -->
<!ELEMENT   beleg-text  (#PCDATA | lemma-beleg | redaktion-ergaenzung | lesart | hervorhebung | sigle | %textauszeichnungen;)* >
<!ELEMENT  redaktion-ergaenzung  (#PCDATA | %textauszeichnungen;)* >  <!-- redaktionelle Ergänzungen des Artikelverfassers; die runden Klammern werden generiert -->
<!ELEMENT   lemma-beleg  (#PCDATA) > <!-- das Vorkommen des Lemmas im Belegtext, erfasst wird die Langform; die Kurzform kommt in das Attribut kurzform -->
<!ELEMENT  lesart  (#PCDATA | redaktion-ergaenzung)* > <!--  verschiedene Lesarten/Lemmavarianten, die hier mit aufgeführt werden  -->
<!ELEMENT  hervorhebung  (#PCDATA) >  <!-- kleine Eckchen vor einer runden Klammer, die als Lesart bezeichnet wird -->
<!ELEMENT  sigle  (#PCDATA) > <!--  Sigle einer Literaturstelle -->
<!ATTLIST  lemma-beleg  kurzform  CDATA  #IMPLIED  >

<!-- Textauszeichnung an verschiedenen Stellen -->
<!ELEMENT   kursiv  (#PCDATA | gerade)* >
<!ELEMENT   gesperrt  (#PCDATA) >
<!ELEMENT   gerade  (#PCDATA | kursiv)* >
<!ELEMENT   hoch  (#PCDATA) >

=== jecki/DHParser/examples/MLW/XML/fascitergula.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MLW-test SYSTEM "../DTD/MLW-DTD_2017-07-12.dtd">
<MLW-test>
    <artikel xml:id="facitergula">
        <!-- Lemma-Ansatz -->
        <!-- nur ein Lemma  -->
        <lemma-position>
            <lemma klassisch="nein" gesichert="nein">facitergula</lemma>
            <!-- Lemmavarianten -->
            <lemma-varianten>
                <lemma-variante kurz="fasc-">fascitergula</lemma-variante>
                <lemma-variante kurz="-iet-">facietergula</lemma-variante>
                <lemma-variante kurz="-ist-">facistergula</lemma-variante>
                <lemma-variante kurz="-rcu-">facitercula</lemma-variante>
                <zusatz typ="sim"></zusatz>
            <lemma-varianten>
            <!-- Grammatik            -->
            <grammatik-position>
                <!-- Grammatik fürs Lemma                 -->
                <grammatik wortart="nomen" genus="f" klasse="a-ae">-ae</grammatik>
                <!-- Grammatik für die Varianten                -->
                <grammatik-varianten>
                    <grammatik-variante>
                        <grammatik wortart="nomen" genus="m" klasse="us-i">-us, -i</grammatik>
                        <beleg id="facitergula-001">
                            <verweis typ="beleg" ziel="facitergula_003"></verweis>
                            <!-- l. 8 -->
                        </beleg>
                    </grammatik-variante>
                    <grammatik-variante>
                        <grammatik wortart="nomen" genus="m" klasse="um-i">-um, -i</grammatik>
                        <beleg id="facitergula-beleg002">
                            <verweis typ="beleg" ziel="facitergula_002"></verweis>
                            <!-- l. 6.11 = Mehrfachverweis -->
                        </beleg>
                        <beleg id="facitergula-beleg002b">
                            <verweis typ="beleg" ziel="facitergula_008"></verweis>
                            <!-- l. 6.11 = Mehrfachverweis -->
                        </beleg>
                    </grammatik-variante>
                </grammatik-varianten>
            </grammatik-position>
            <!-- Etymologie-Position: hier nicht vorhanden         -->
        </lemma-position>
        <!--  Artikelkopf -->
        <artikelkopf>
            <!-- Schreibweisen des Lemmas            -->
            <schreibweisen-position>
                <schreibweisen-variante>
                    <schreibweise-besonderheit typ="script"></schreibweise-besonderheit>
                    <!--wenn nur eine Schreibweise, dann nach "script." KEIN Doppelpunkt, sonst schon!-->
                    <schreibweise>vizreg-</schreibweise>
                    <beleg id="facitergula-beleg003">
                        <verweis typ="beleg" ziel="facitergula_013"></verweis>
                    </beleg>
                </schreibweisen-variante>
                <schreibweisen-variante>
                    <schreibweise-besonderheit typ="script"></schreibweise-besonderheit>
                    <schreibweise>festregel(a)</schreibweise>
                    <beleg id="facitergula-beleg004">
                        <verweis typ="beleg" ziel="facitergula_010"></verweis>
                    </beleg>
                </schreibweisen-variante>
                <schreibweisen-variante>
                    <schreibweise-besonderheit typ="script"></schreibweise-besonderheit>
                    <schreibweise>fezdregl(a)</schreibweise>
                    <beleg id="facitergula-beleg005">
                        <verweis typ="beleg" ziel="facitergula_008"></verweis>
                    </beleg>
                </schreibweisen-variante>
            </schreibweisen-position>
        </artikelkopf>
        <!-- Hauptteil -->
        <bedeutung-position>
            <!-- nur eine Bedeutungsposition in jedem Artikel -->
            <!-- 1. Bedeutung -->
            <bedeutung nr="1">
                <interpretament typ="lat">pannus, faciale, sudarium</interpretament>
                <interpretament-deutsch>(Gesichts-, Schweiß-)Tuch</interpretament-deutsch>
                <interpretament-zusatz>usu liturg.</interpretament-zusatz>
                <interpretament-zusatz>de re v.                     
                    <verweis typ="beleg" ziel="???"></verweis>p. 32,63
                
                </interpretament-zusatz>
                <!--                Belege für die 1. Bedeutung -->
                <beleg-position>
                    <!--                    Beleg 1 -->
                    <beleg id="facitergula_beleg001">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>28,11</stelle>
                            <datierung>Post 851</datierung>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg kurzform="-um">facitergulum</lemma-beleg> Ill.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 2 -->
                    <beleg id="facitergula_beleg002">
                        <beleg-quelle>
                            <autor>Form.</autor>
                            <werk>Sangall.</werk>
                            <stelle>39 p. 421,16</stelle>
                        </beleg-quelle>
                        <beleg-text>munuscula ... direximus, hoc est palliolum ...,                             
                            <lemma-beleg kurzform="-as">facitergulas</lemma-beleg> duas.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 3 -->
                    <beleg id="facitergula_beleg003">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>18,7</stelle>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg kurzform="-eterculi">faciterculi</lemma-beleg> viginti quatuor.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 4 -->
                    <beleg id="facitergula_beleg004">
                        <beleg-quelle>
                            <autor>Libri</autor>
                            <werk>confrat. I</werk>
                            <stelle>app. A 6 p. 137,30</stelle>
                        </beleg-quelle>
                        <beleg-text>pulpitum ...                             
                            <lemma-beleg kurzform="-a">facitergula</lemma-beleg> cocco imaginata circumdari iussit                             
                            <redaktion-ergaenzung>pontifex</redaktion-ergaenzung>.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 5 -->
                    <beleg id="facitergula_beleg005">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>76,15</stelle>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg kurzform="-rulae">faciterulae</lemma-beleg> Il.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 6 -->
                    <beleg id="facitergula_beleg013">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>40,5 VI</stelle>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg>vizregule</lemma-beleg>.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 7 -->
                    <beleg id="facitergula_beleg006">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>129
                                
                                <hoch>a</hoch>,5
                            
                            </stelle>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg kurzform="-sterculas">facisterculas</lemma-beleg> Il.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 8 -->
                    <beleg id="facitergula_beleg007">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>24,8</stelle>
                        </beleg-quelle>
                        <beleg-text>
                            <lemma-beleg kurzform="-itella">facitella</lemma-beleg> X.
                        
                        </beleg-text>
                    </beleg>
                    <!--                    Beleg 9 -->
                    <beleg id="facitergula_beleg008">
                        <beleg-quelle>
                            <autor>Catal.</autor>
                            <werk>thes. Germ.</werk>
                            <stelle>114,8</stelle>
                        </beleg-quelle>
                        <beleg-text>VIII                             
                            <lemma-beleg>fezdregle</lemma-beleg>.
